[package]
name = "experiment_5_3"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
rayon = "1.8"
bio = "2.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "2.0.1"
clap = { version = "4.0", features = ["derive"] }
