[package]
name = "experiment_21_6"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.23.5", features = ["extension-module"] }

[lib]
name = "pyo3_biopython_example"
crate-type = ["cdylib"]
