[package]
name = "transcript_counter"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
rust-htslib = "0.49.0"
rayon = "1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.3", features = ["derive"] }