[package]
name = "vcf_analysis"
version = "0.1.0"
edition = "2024"

[dependencies]
rust-htslib = "0.49.0"
rayon = "1.5.1"
ndarray = "0.16.1"
statrs = "0.18.0"
polars = { version = "0.46", features = ["lazy"] }