[package]
name = "experiment_3_1_6"
version = "0.1.0"
edition = "2021"

[dependencies]
needletail = "0.6.3"  # For parsing FASTA/FASTQ files
serde = { version = "1.0", features = ["derive"] }  # For serializing/deserializing data
serde_json = "1.0"  # For writing JSON output
