[package]
name = "experiment_3.6_2"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = "1.3.3"  # Use this version to avoid breaking changes
