[package]
name = "experiment_3_4"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.7"
needletail = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bitvec = "1.0.1"
