[package]
name = "kmer_debruijn_builder"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
rayon = "1.8"
needletail = "0.6.3"
fnv = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "2.0.1"
clap = { version = "4.4", features = ["derive"] }