[package]
name = "experiment_64"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
log = "0.4"
env_logger = "0.11.8"
rayon = "1.7"
rust-htslib = "0.49.0"
