[package]
name = "experiment_4.8"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rayon = "1.10.0"
reqwest = { version = "0.12.14", features = ["blocking", "json"] }
