[package]
name = "rust_vcf_merge_tool"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
rayon = "1.5"
rust-htslib = "0.49"
env_logger = "0.11.8"
log = "0.4"