[package]
name = "experiment_5.1_3"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
