[package]
name = "experiment_1_4"
version = "0.1.0"
edition = "2021"

[dependencies]
linfa = "0.7.1"
linfa-clustering = "0.7.1"
tch = "0.19.0"
anyhow = "1.0"
thiserror = "2.0.11"
ndarray = { version = "0.15", features = ["approx"] }
